from enum import StrEnum


class Intent(StrEnum):
    PRODUCT_DISCOVERY = "PRODUCT_DISCOVERY"
    PRODUCT_COMPARE = "PRODUCT_COMPARE"
    PRODUCT_DETAIL = "PRODUCT_DETAIL"

    KNOWLEDGE_QA = "KNOWLEDGE_QA"

    CART_STATUS = "CART_STATUS"
    ORDER_STATUS = "ORDER_STATUS"
    PAYMENT_STATUS = "PAYMENT_STATUS"

    WARRANTY_STATUS = "WARRANTY_STATUS"
    WARRANTY_TICKET_STATUS = "WARRANTY_TICKET_STATUS"

    GREETING = "GREETING"
    HELP = "HELP"
    UNKNOWN = "UNKNOWN"


class RequestedField(StrEnum):
    PRICE = "PRICE"
    STOCK = "STOCK"
    PROMOTION = "PROMOTION"
    SPECIFICATIONS = "SPECIFICATIONS"
    WARRANTY = "WARRANTY"
    REVIEWS = "REVIEWS"
    PAYMENT_STATUS = "PAYMENT_STATUS"

class MessageRole(StrEnum):
    USER = "USER"
    ASSISTANT = "ASSISTANT"