spring:
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    open-in-view: false

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

app:
  seed:
    goods-receipt:
      enabled: ${APP_SEED_GOODS_RECEIPT_ENABLED:${GOODS_RECEIPT_SEED_ENABLED:false}}
